app/models.py
from . import db
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from . import login_manager
from datetime import datetime
@login_manager.user_loader
def load_user(user_id):
    return User.query.get (user_id)
class User(UserMixin,db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255))
    email = db.Column(db.String(255),unique = True,index = True)
    pass_secure = db.Column(db.String(255))
    bloges= db.relationship('Blog',backref = 'user',lazy = "dynamic")
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())
    password_secure = db.Column(db.String(255))
    @property
    def password(self):
            raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
            self.pass_secure = generate_password_hash(password)


    def verify_password(self,password):
            return check_password_hash(self.pass_secure,password)
    def __repr__(self):
        return f'User {self.username}'

class Blog(db.Model):

    __tablename__ ='bloges'

    id = db.Column(db.Integer,primary_key = True)
    title = db.Column(db.String)
    description=db.Column(db.Text)
    category=db.Column(db.String(255),nullable=False)
    user_id = db.Column(db.Integer,db.ForeignKey("users.id")) 
    
    
    def save_blog(self):
        db.session.add(self)
        db.session.commit()
    @classmethod
    def get_bloges(cls,id):
        bloges = Bloges.query.filter_by(blog_id=id).all()
        return bloges
    def delete_post(self):
       db.session.delete(self)
       db.session.commit()
    
    def __repr__(self):
        return f'blog {self.description}'

class Comment(db.Model):
    __tablename__='comments'
    
    id = db.Column(db.Integer,primary_key=True)
    blog_id = db.Column(db.Integer, db.ForeignKey('bloges.id'), nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable= False)
    description = db.Column(db.Text)

    def __repr__(self):
        return f"Comment : id: {self.id} comment: {self.description}"

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField,ValidationError,PasswordField,RadioField
from wtforms.validators import Required,Email,EqualTo
from ..models import User

class RegistrationForm(FlaskForm):
    email = StringField('Your Email Address',validators=[Required(),Email()])
    username = StringField('Enter your username',validators = [Required()])
    password = PasswordField('Password',validators = [Required(), EqualTo('password_confirm',message = 'Passwords must match')])
    password_confirm = PasswordField('Confirm Passwords',validators = [Required()])
    submit = SubmitField('Sign Up')
    def validate_email(self,data_field):
            if User.query.filter_by(email =data_field.data).first():
                raise ValidationError('There is an account with that email')

    def validate_username(self,data_field):
        if User.query.filter_by(username = data_field.data).first():
            raise ValidationError('That username is taken')


class BlogForm(FlaskForm):
    title = TextAreaField('Title',validators = [Required()])
    description = TextAreaField(" the blog you need",validators=[Required()])
    submit = SubmitField('Submit')
    category = RadioField('Label', choices=[ ('productpitch','productpitch')],validators=[Required()])
class CommentForm(FlaskForm):
	description = TextAreaField('Add comment',validators=[Required()])
	submit = SubmitField()

class UpdateProfileForm(FlaskForm):
    bio = TextAreaField('Tell us about your you.',validators = [Required()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_mail import Mail
from flask_simplemde import SimpleMDE
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

bootstrap = Bootstrap()
db = SQLAlchemy()
photos = UploadSet('photos',IMAGES)
mail=Mail()
simple = SimpleMDE()
def create_app(config_name):

    app = Flask(__name__)
    simple.init_app(app)
     # Creating the app configurations

    app.config.from_object(config_options[config_name])
    config_options[config_name].init_app(app)
     # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)

   # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix='/auth')
   
    
    # # setting config
    # from .request import configure_request
    # configure_request(app)

    # configure UploadSet
    configure_uploads(app,photos)

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,errors

app/main/views.py
from flask import render_template,request,redirect,url_for,abort
from . import main
from .forms import BlogForm,UpdateProfileForm
from ..models import User,Comment,Blog                      
from flask_login import login_required,current_user
from .. import db



# Views
@main.route('/')
def index():
  
    '''
    View root page function that returns the index page and its data
    '''
    
    
    title = 'Welcome'
    productblog = Blog.query.filter_by(category = "productblog")
    return render_template('index.html', title = title,productblog=productblog)

@main.route('/bloges/new/', methods = ['GET','POST'])
@login_required
def new_blog():
    form = BlogForm()
    # my_updates = Update.query.filter_by(blog_id = blog.id)
    if form.validate_on_submit():
        description = form.description.data
        title = form.title.data
        user_id = current_user
        category = form.category.data
        print(current_user._get_current_object().id)
        new_blog = Blog(user_id =current_user._get_current_object().id, title = title,description=description,category=category)
        db.session.add(new_blog)
        db.session.commit()
        
        return redirect(url_for('main.index'))
    return render_template('blog.html',form=form)

@main.route('/comment/new/<int:blog_id>', methods = ['GET','POST'])
@login_required
def new_comment(blog_id):
    form = CommentForm()
    blog=Blog.query.get(blog_id)
    if form.validate_on_submit():
        description = form.description.data

        new_comment = Comment(description = description, user_id = current_user._get_current_object().id, blog_id = blog_id)
        db.session.add(new_comment)
        db.session.commit()


        return redirect(url_for('.new_comment', blog_id= blog_id))

    all_comments = Comment.query.filter_by(blog_id = blog_id).all()
    return render_template('comments.html', form = form, comment = all_comments, blog = blog )
@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():

        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username))

    return render_template('profile/update.html',form =form)

@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile',uname=uname))

@main.route('/delete_blog/<int:blog_id>',methods= ['POST','GET'])
@login_required
def delete_blog(blog_id):
  blog= blog.query.filter_by(id = blog_id).first()
  comments=blog.comments
  if blog.comments:
    for comment in comments:
        db.session.delete(comment)
        db.session.commit()
  user = current_user
  db.session.delete(post)
  db.session.commit()
  return redirect(url_for('main.index'))
  return render_template('index.html', user=user)

app/templates/base.html
{% extends 'bootstrap/base.html'%}

<!-- Navbar block  --> 
{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}
{% block content %}
   
    {% endblock %} 
    {%block styles %}
    
    {% endblock %}  
    <!--Importing the simple mde css and js files  -->
    {{ simplemde.css}}
    {{ simplemde.js }}
    

app/templates/blog.html
{% import 'bootstrap/wtf.html' as wtf %}
{% extends 'bootstrap/base.html' %}
{% include 'navbar.html' %}

{% block content %}

<div class="container">
<div class="row">
<div class="jumbotron">

     {{wtf.quick_form(form)}}
	<ul style="list-style: none;">
    {% for blog in bloges %}
<div class="list-group">
	<a href="#">
<div class="list-item">
		<p>{{blog.id}}</p>
</div>
	<h4>{{ blog.description }}</h4>
	<h6> Posted by {{user.username}}.</h6>
	</a>
</div>
	{% endfor %}
	</ul>
</div>
</div>
</div>
		
{% endblock %}

app/templates/comments.html
{% include 'navbar.html'%}

{% import 'bootstrap/wtf.html' as wtf %}
{% extends 'bootstrap/base.html' %}
{% import 'macros.html' as macro %}

{% block content %}
          
<div class="row">
<div class="card">
<div class="card-body text-center">
<h3><a>{{blog.title}}</a></h3>
<h4 class="card-text text-center">{{blog.description}}.</h4>
</div>
</div>
<div class="container">
<div class="row">
<div class="jumbotron">
  {{wtf.quick_form(form)}}
</div>
</div>
</div>      
<hr><hr>
<div class="container">
<div class="col-md-12">
<h3 style="color: skyblue; text-align: center;text-underline-position: below"> Your Comments</h>
    {{ macro.displayComment(comment) }}
</div>
 </div>
</div>



	
{% endblock %}

app/templates/fourOwfour.html
{% extends 'base.html'%}

{% block content %}
    <h1>WHOOOPS we can't find that page</h1>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}
{% import 'macros.html' as macro %}
{% block styles %}
    
    <link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
    <link href="https://fonts.googleapis.com/css?family=Sacramento&display=swap" rel="stylesheet">
{% endblock %}
{% block content %}

<div class="container-fluid" style="background-image: url('');width:60%;background-repeat: no-repeat;">
        <div class="container"></div>
<h3 > Welcome to blog</h3>
 <p style="border: 2px solid black;padding:50px;border-radius: 25px;font-family:serfix;width: 25%;">Stay positive even when it feels like <br>yourwhole world is falling apart <br> the many will start fast,few will finish strong </p>      
</div>
<h3 style="color: rgb(7, 7, 7);text-align: center">Blog Category</h3>
      
      <ul class="nav nav-pills nav-justified nav-fill" role="tablist">
        <li class="nav-item">
          <a class="nav-link active" data-toggle="tab" href="#product" style="color: rgb(5, 5, 5);">Product</a>
        </li>
        <div class="tab-content">
            <div id="product" class="container tab-pane fade">
              {{ macro.display(productblog) }}
              
            </div>
        
    
<div class="row">
<div class="col-md-12 welcome">
    {% if current_user.is_authenticated %}
    <a id="start" class="btn btn-danger animated infinite flash" href="{{url_for('main.index')}}">See all blogese</a>
    {% else %}
    <a id="start" class="btn btn-danger animated infinite flash" href="{{url_for('auth.login')}}">Sign In</a>
    {% endif %}
 
    </div>
</div>
</div>


{% endblock %}

app/templates/macros.html
        {% macro display(category_list) %}<div class="row">
		{% if category_list %}
		   {% for category in category_list %}
	<div class="col-md-6">
	<div class="thumbnail text-center">
		<h4 class="card-header">{{category.title}}</h4>
		<h4 class="card-header">{{category.category}}</h4>
	<div class="card-body">
		<blockquote class="blockquote mb-0">
		<h2>{{category.description}}</h2>				
		<footer class="blockquote-footer"> Posted by {{category.user.username}}</footer>
		</blockquote>
		<a href="{{url_for('main.new_comment',blog_id = category.id)}}" class="btn btn-info"> Add comment</a>		
	</div>
</div>

</div>
	{% endfor %}
	{% else %}
	{% endif %}
</div>



<ul>
	{% if comments %}
	{% for comment in comments %}
<div class="row text-center">
   <a><p style="color: brown">{{ comment.description }}</p></a>
   <small> posted by {{comment.user.username}}</small>
</div>
   {% endfor %}
   {% else %}

   <h3>This post does  not does not have any comments yet !</h3>
	{%endif%}

	</ul>
	
{% endmacro %}

app/templates/navbar.html
<div style="background-image:url('https://i.pinimg.com/originals/f2/50/62/f25062b96c7c06f256ad232a84916550.jpg');opacity:0.7;height:500px;width:900%;background-repeat: no-repeat;")>
    <div class="navbar navbar" role="navigation">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                      <span class="sr-only">Toggle navigation</span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                    </button>
                  
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="/">Home</a></li>
                    </ul>
                    <ul>
                        
                      <a style="text-align: center; color:black;" class="navbar-brand" href="/">All Blogs </a>
                      <ul>
                        <a style="text-align: center; color:black;" class="navbar-brand" href="/bloges/new/"> Add Blogs </a>
                        </ul>
                      </ul>
                     
                </div>
    
            </div>
             <ul class="nav navbar-nav navbar-right">
            {% if current_user.is_authenticated %}
            <li style = "color:black;padding:15px;">{{current_user.username}}</li>
            
            <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
            {% else %}
            <li><a href="{{url_for('auth.login')}}">Sign in</a></li>
            {%endif%}
          </ul>
        </div>
    </div>
    
         

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
<div class="row">
<!-- displaying  Username-->
  <div class="col-md-4">
    <h3> {{user.username| capitalize}} </h3>

    <!--Displaying user bio-->
    {% if user.bio %}
      <p> {{user.bio}}</p>
    {%else%}
      <p> {{user.username| capitalize}} has no bio </p>
    {% endif %}
  </div>

  <!--Display profile photo-->
  <div class="col-md-4">

    {% if user.profile_pic_path %}
    <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">
    {%else%}
    <p>No profile picture</p>
    {% endif %}
    {% if user == current_user %}
    <form  action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype = "multipart/form-data">

        <input type="file"  name="photo" class="form-control" required>
        <input type="submit">
      </form>
    {% endif %}
  </div>

</div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
  {{wtf.quick_form(form)}}
{% endblock %}